

package Vista;

import Controlador.Controlador_FRM_MenuPrincipal;
import Modelo.ConexionBD;


public class FRM_MenuPrincipal extends javax.swing.JFrame {

    
    Controlador_FRM_MenuPrincipal controlador_FRM_MenuPrincipal;
    ConexionBD conexion;
    public FRM_MenuPrincipal() {
        initComponents();
        setLocation(150,150);
        controlador_FRM_MenuPrincipal= new Controlador_FRM_MenuPrincipal();
         this.conexion =new ConexionBD();
        agregarEventos();
    }
   public void agregarEventos(){
       this.jm_Salir.addActionListener(controlador_FRM_MenuPrincipal);
       this.jm_Matricula.addActionListener(controlador_FRM_MenuPrincipal);
       this.jm_ResgistroEstudiantes.addActionListener(controlador_FRM_MenuPrincipal);
       this.jm_Cursos.addActionListener(controlador_FRM_MenuPrincipal);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_Archivo = new javax.swing.JMenu();
        jm_Salir = new javax.swing.JMenuItem();
        jm_Menu = new javax.swing.JMenu();
        jm_ResgistroEstudiantes = new javax.swing.JMenuItem();
        jm_Matricula = new javax.swing.JMenuItem();
        jm_Cursos = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jm_Archivo.setText("Archivo");

        jm_Salir.setText("Salir");
        jm_Archivo.add(jm_Salir);

        jMenuBar1.add(jm_Archivo);

        jm_Menu.setText("Menú");

        jm_ResgistroEstudiantes.setText("Registro Estudiantes");
        jm_Menu.add(jm_ResgistroEstudiantes);

        jm_Matricula.setText("Matricula");
        jm_Menu.add(jm_Matricula);

        jm_Cursos.setText("Registro Cursos");
        jm_Menu.add(jm_Cursos);

        jMenuBar1.add(jm_Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FRM_MenuPrincipal baseDatos= new FRM_MenuPrincipal();
                new FRM_MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jm_Archivo;
    private javax.swing.JMenuItem jm_Cursos;
    private javax.swing.JMenuItem jm_Matricula;
    private javax.swing.JMenu jm_Menu;
    private javax.swing.JMenuItem jm_ResgistroEstudiantes;
    private javax.swing.JMenuItem jm_Salir;
    // End of variables declaration//GEN-END:variables
}
