/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_RegistroEstudiantes;
import javax.swing.JOptionPane;


public class FRM_RegistroEstudiantes extends javax.swing.JFrame {

    /**
     * Creates new form FRM_RegistroEstudiantes
     */
    public Controlador_FRM_RegistroEstudiantes controlador_FRM_RegistroEstudiantes;// que sea accesible
    public FRM_RegistroEstudiantes() {
        initComponents();
        setVisible(false);
        controlador_FRM_RegistroEstudiantes= new Controlador_FRM_RegistroEstudiantes(this);
        gUI_Botones1.agregarEventos(controlador_FRM_RegistroEstudiantes);
        this.gUI_InformacionEstudiante1.agregarEventos(controlador_FRM_RegistroEstudiantes);
        estadoInicial();
    }
    
   public String[] devolverInformacion(){
       return this.gUI_InformacionEstudiante1.devolverInformacion();
   }

    public void setgUI_Botones1(GUI_Botones gUI_Botones1) {
        this.gUI_Botones1 = gUI_Botones1;
    }

    public void setgUI_InformacionEstudiante1(GUI_InformacionEstudiante gUI_InformacionEstudiante1) {
        this.gUI_InformacionEstudiante1 = gUI_InformacionEstudiante1;
    }
   
   public String devolverCarnet(){
       return this.gUI_InformacionEstudiante1.devolverCarnet();
    }
   public String devolverNombre(){
       return this.gUI_InformacionEstudiante1.devolverNombre();
    }
 
   public void mostrarInformacion(String arreglo[]){
       this.gUI_InformacionEstudiante1.mostrarInformacion(arreglo);
    }
   public void mostrarMensaje(String mensaje){
       JOptionPane.showMessageDialog(null,mensaje);
   }
   public void limpiaInterfaz(){
       this.gUI_InformacionEstudiante1.limpiarInterfaz();
   }
   public void estadoInicial(){
       this.gUI_InformacionEstudiante1.estadoInicial();
       this.gUI_Botones1.estadoInicialBotones();
   }
   public void habilitarExiste(){
       this.gUI_InformacionEstudiante1.hablilitarSiExiste();
       this.gUI_Botones1.habilitarExisteBotones();
   }
   public void habilitarDesconocido(){
      gUI_InformacionEstudiante1.habilitarNoExiste();
      gUI_Botones1.habilitarNoExisteBotones();
   }
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_InformacionEstudiante1 = new Vista.GUI_InformacionEstudiante();
        gUI_Botones1 = new Vista.GUI_Botones();

        setMinimumSize(new java.awt.Dimension(700, 323));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(gUI_InformacionEstudiante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(gUI_InformacionEstudiante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
     // controlador_FRM_RegistroEstudiantes.agregarInformacionAlArchivo();
    }//GEN-LAST:event_formComponentHidden



    /**
     * 
     * 
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private Vista.GUI_InformacionEstudiante gUI_InformacionEstudiante1;
    // End of variables declaration//GEN-END:variables
}
