
package Vista;

import Controlador.Controlador_FRM_RegistroEstudiantes;
import javax.swing.JTextField;


public class GUI_InformacionEstudiante extends javax.swing.JPanel {

    /**
     * Creates new form GUI_InformacionEstudiante
     */
    Controlador_FRM_RegistroEstudiantes controlador;
    public GUI_InformacionEstudiante() {
        initComponents();
    }
  public String[] devolverInformacion(){
       String arreglo[];
       arreglo=new String[2];
       arreglo[0]=this.jt_Carnet.getText();
       arreglo[1]=this.jt_Nombre.getText();
       
              return arreglo;
   }
   public void agregarEventos(Controlador_FRM_RegistroEstudiantes controlador)
   {
   this.jb_ConsultaRapida.addActionListener(controlador);
   this.controlador=controlador;
   }
   
public String devolverCarnet(){
    return this.jt_Carnet.getText();
}
public String devolverNombre(){
    return this.jt_Nombre.getText();
}

public void mostrarInformacion(String arreglo[]){
    //this.jt_Carnet.setText(arreglo[0]);
    this.jt_Nombre.setText(arreglo[1]);
}

public void limpiarInterfaz(){
    this.jt_Carnet.setText("");
    this.jt_Nombre.setText("");
}

public void estadoInicial(){
    this.jt_Carnet.setEnabled(true);
    this.jt_Nombre.setEnabled(false);
}
public void hablilitarSiExiste(){
    this.jt_Carnet.setEnabled(false);
    this.jt_Nombre.setEnabled(true);
}
public void habilitarNoExiste(){
    this.jt_Carnet.setEnabled(true);
    this.jt_Nombre.setEnabled(true);
}

    /* This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Carne = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();
        jt_Carnet = new javax.swing.JTextField();
        jt_Nombre = new javax.swing.JTextField();
        jb_ConsultaRapida = new javax.swing.JButton();

        setOpaque(false);

        jl_Carne.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_Carne.setText("Carné");

        jl_Nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_Nombre.setText("Nombre");

        jt_Carnet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_CarnetKeyPressed(evt);
            }
        });

        jb_ConsultaRapida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consulta.png"))); // NOI18N
        jb_ConsultaRapida.setText("Consulta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_Nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jt_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addGap(97, 97, 97))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_Carne)
                        .addGap(27, 27, 27)
                        .addComponent(jt_Carnet)
                        .addGap(18, 18, 18)))
                .addComponent(jb_ConsultaRapida)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Carne)
                    .addComponent(jt_Carnet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_ConsultaRapida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jt_CarnetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_CarnetKeyPressed
        if(evt.getKeyCode()==10){
            this.controlador.buscar();
        }
    }//GEN-LAST:event_jt_CarnetKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_ConsultaRapida;
    private javax.swing.JLabel jl_Carne;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JTextField jt_Carnet;
    private javax.swing.JTextField jt_Nombre;
    // End of variables declaration//GEN-END:variables
}
