
package Vista;

/**
 *
 * @author Tata
 */
public class GUI_InformacionCursos extends javax.swing.JPanel {

    /**
     * Creates new form GUI_InformacionCursos
     */
    public GUI_InformacionCursos() {
        initComponents();
        cargarCreditos();
    }
    
    public String[] devolverInformacion(){
    String arreglo[];
    arreglo=new String[4];
    arreglo[0]=this.jt_Sigla.getText();
    arreglo[1]=this.jt_NombreCurso.getText();
    arreglo[2]=""+this.jcb_Creditos.getSelectedIndex();
    arreglo[3]=this.jt_Horario.getText();
    
    return arreglo;
}
public void estadoInicio(){
    this.jt_Sigla.setEnabled(true);
    this.jt_NombreCurso.setEnabled(false);
    this.jt_Horario.setEnabled(false);
    this.jcb_Creditos.setEnabled(false);
}
public void ExistenCurso(){
    this.jt_Sigla.setEnabled(false);
    this.jt_Horario.setEnabled(true);
    this.jcb_Creditos.setEnabled(true);
    this.jt_NombreCurso.setEnabled(true);
}
public void NoHayCursos(){
     this.jt_Sigla.setEnabled(true);
    this.jt_Horario.setEnabled(true);
    this.jcb_Creditos.setEnabled(true);
    this.jt_NombreCurso.setEnabled(true);
}

public void limpiarInterfaz(){
    this.jl_NombreCurso.setText("");
    this.jt_Horario.setText("");
  
    this.jt_Sigla.setText("");
    
}
public String devolverSigla(){
    return this.jt_Sigla.getText();
}
public String devolverNombreCurso(){
return    this.jt_NombreCurso.getText();
}
public String devolverCreditos(){
    return ""+this.jcb_Creditos.getSelectedIndex();
}
public String devolverHorario(){
    return this.jt_Horario.getText();
}
public void cargarCreditos(){
    this.jcb_Creditos.removeAllItems();
    for(int contador=0;contador<10;contador++){
this.jcb_Creditos.addItem(""+contador);    
    }
    this.jcb_Creditos.setSelectedIndex(4);//LOS ARREGLOS COMIENZAN DESDE 0 QUIERO QUE SALGA 5 NUMEROS ENTONCES PONGO 4 ESPACIOS 01234
}

public void mostrarInformacion(String arreglo[]){
    this.jt_NombreCurso.setText(arreglo[0]);
     this.jcb_Creditos.setSelectedIndex(Integer.parseInt(arreglo[1]));
     this.jt_Horario.setText(arreglo[2]);
}


/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jl_NombreCurso = new javax.swing.JLabel();
        jt_NombreCurso = new javax.swing.JTextField();
        jl_Sigla = new javax.swing.JLabel();
        jt_Sigla = new javax.swing.JTextField();
        jl_Creditos = new javax.swing.JLabel();
        jl_Horario = new javax.swing.JLabel();
        jt_Horario = new javax.swing.JTextField();
        jcb_Creditos = new javax.swing.JComboBox();

        jTextField1.setText("jTextField1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_NombreCurso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_NombreCurso.setText("Nombre Curso");
        add(jl_NombreCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        add(jt_NombreCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 230, 28));

        jl_Sigla.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_Sigla.setText("Sigla");
        add(jl_Sigla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        add(jt_Sigla, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 230, 29));

        jl_Creditos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_Creditos.setText("Créditos");
        add(jl_Creditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 147, -1, -1));

        jl_Horario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_Horario.setText("Horario");
        add(jl_Horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));
        add(jt_Horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 230, 30));

        jcb_Creditos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jcb_Creditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 210, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox jcb_Creditos;
    private javax.swing.JLabel jl_Creditos;
    private javax.swing.JLabel jl_Horario;
    private javax.swing.JLabel jl_NombreCurso;
    private javax.swing.JLabel jl_Sigla;
    private javax.swing.JTextField jt_Horario;
    private javax.swing.JTextField jt_NombreCurso;
    private javax.swing.JTextField jt_Sigla;
    // End of variables declaration//GEN-END:variables
}
